- components/_util/lang.js
- components/field-item/index.vue
Hi admin, I used MD and found that it cannot work in old version browser.
I fork it and found that you use **(Exponentiation assignment) in your code which is a feature of the ECMAScript 2016. so I replace it with Math.pow
> replace ** with Math.pow

- components/dialog/dialog.vue
Dialog body text is align left by default. If there has only one line, make it align center.
> fix(dialog): text align center only if there has one line

- types/index.d.ts
The CellItem component is not defined in index.d.ts.
> fix(types): Add the CellItem component to index.d.ts

- components/scroll-view/README.en-US.md
- components/scroll-view/README.md
- components/scroll-view/index.vue
limit the angle at which triggers scroll events to reduce scroll sensitivity
> feat(scroll-view): add prop touch-angle

- components/scroll-view/index.vue
When finger move outside mobile device screen, `touchend` event is not fired, which cause `scroll-view` is not trigger move end action. This PR is try to fix this problem.
> Fix scroll-view boundary bug

- components/input-item/README.en-US.md
- components/input-item/README.md
- components/input-item/demo/cases/demo4.vue
- components/input-item/index.vue
use ref name to look up a component instance in context instead of passing a reference directly
#355
> fix(input-item): change virtualKeyboardVm type to string

- components/codebox/index.vue
> fix(codebox): fix the bottom border of codebox is not visible in oppo r9m

- components/swiper/index.vue
- components/swiper/test/index.spec.js
is-loop为true时，调用`goto`时跳转异常
*  区分`real index`(swiper内部items的真实索引)，`display index`(用户视角的swiper index)
* 增加两个方法`$_calcDisplayIndex`(将`display index`转换为`real index`)，`$_calcRealIndex`(将`real index`转换为`display index`)
* 调用goto时，先把`display index`转换为`real index`
* 调用goto时，需重启定时器，否则跳转完可能会立马又跳走
> fix(swiper): fix incorrect index jumping with method goto

- components/input-item/README.en-US.md
- components/input-item/README.md
- components/input-item/index.vue
标题宽度有时需要不固定
增加属性`solid`，默认为`true`
> feat(input-item):add prop solid to custom title width

- components/steps/README.en-US.md
- components/steps/README.md
- components/steps/demo/cases/demo2.vue
- components/steps/index.vue
自定义图标功能不全且过于复杂
增加新slot icon，用于统一自定义全部步骤图标
增加新slot unreached，用于自定义未完成步骤图标
> feat(steps):support unreached step icon customization & unify customization

- components/radio/list.vue
radio-list 使用时，先在input中输入，再选择radio时，input并没有置空
radio-list 使用时，先在input中输入，再选择radio时，input置空
无
> fix(radio-list): clear input item when changing selected option

- components/date-picker/index.vue
DatePicker中的小时目前只支持24小时制，但custom-types中的小时用hh表示，所以增加HH支持
1. custom-types 中支持 HH
2. getFormatDate 中支持 HH
回归
> fix(date-picker): support HH in custom-types

- components/tab-picker/README.en-US.md
- components/tab-picker/README.md
- components/tab-picker/index.vue
1. 目前只有一个全部tab选项选择完成的`change`事件，缺乏每一级tab选中事件 #435 
2. 上一级tab选中时可能会滚动容器(`ScrollView`)，选中某项后切换到下一级tab，容器未回到顶部
1. 选项选中时，触发select事件
2. 选项选中后，`ScrollView`滚回顶部
回归
> feat(tab-picker):add select event & optimize container scrolltop

- components/tab-bar/index.vue
首尾两个选项位于部分露出的位置时，选中后无法自动滚动至合适位置。
`prevTarget`或`nextTarget`为空时，`scroller`需分别最左侧和最右侧。
无
> fix(tab-bar): supplement scrolling of the first and last options

- components/_style/mixin/util.styl
hairline 原来使用width 和 height 控制尺寸，被转换成rem后会存在无法渲染的问题
将width和height 改成 border-left/right/top/bottom
> fix(style-utils):hairline size optimization

- components/check/README.en-US.md
- components/check/README.md
- components/check/demo/cases/demo5.vue
- components/check/demo/index.vue
- components/check/index.vue
- components/check/list.vue
- components/check/mixin/index.js
- components/check/test/__snapshots__/demo.spec.js.snap
checkList支持icon自定义、icon位置
支持icon自定义、icon位置：新增props
新props
> feat(check-list): support check-list icon slot

- components/radio/list.vue
为 radioList 新增了一个 'noIcon' 的属性， 需要配合 'is-slot-scope' 使用。因为当我们有需求使用 slot-scope 的时候，甚至连 icon 都不需要；当我 把 iconname 都设置为空时，图标区域仍有一个 margin-left 影响布局。同时，slot-scope v-bind的值过少，导致使用不便，我增加了两个新的 props: index, selected 以省去父组件部分的计算内容。
radioList 新增一个 props:  noIcon: boolean
slot-scope 新增两个属性： index: number, selected: boolean
1、radioList 代码
> feat(radioList):add props for slot-scope & add removing icon configration

- components/toast/README.en-US.md
- components/toast/README.md
- components/toast/demo/cases/demo7.vue
- components/toast/demo/index.vue
- components/toast/index.js
- components/toast/toast.vue
- types/toast.d.ts
通过对外暴露`Toast.component`，提供组件化的使用方式，以覆盖需要上层封装的定制场景，如#445 
```html
<md-toast>xxx</md-toast>
```
```javascript
import { Toast } from 'mand-mobile'
export default {
components: {
[Toast.component.name]: Toast.component
}
}
```
- 暴露`Toast.component`
- 增加`show`方法和`show`事件
- `visible`初始值改为`false`
`visible`初始值原来为`true`，导致组件化使用时组件初始化完成就为展示状态，故改为`false`，通过调用`show/hide`方法来控制。但需注意此改动带来的影响
> feat(toast):add Toast.component for componentized usage

- components/scroll-view/README.en-US.md
- components/scroll-view/README.md
- components/scroll-view/demo/cases/demo1.vue
- components/scroll-view/index.vue
通过新增属性`is-prevent`设置，当在非可滚动区域触发滚动时，是否也阻止默认行为。如在横向滚动区域触发纵向滚动，需触发浏览器默认滚动的场景 #454 
增加`is-prevent`，以控制是否调用`touchmove`内部的前置`event.preventDefault()`
> feat(scroll-view): add prop is-prevent

- components/slider/index.vue
fix #472
slider在range为false时，设置min & max，组件显示不正确。因为计算长度的时候并没有将min的值减去导致的。
range为false时，计算barStyle会减去min
无
> fix(slider): fix wrong slider-bar display bug without range in min & max

- components/number-keyboard/README.en-US.md
- components/number-keyboard/README.md
- components/number-keyboard/board.vue
- components/number-keyboard/demo/cases/demo0.vue
- components/number-keyboard/demo/cases/demo1.vue
- components/number-keyboard/demo/cases/demo2.vue
- components/number-keyboard/demo/cases/demo3.vue
- components/number-keyboard/demo/index.vue
- components/number-keyboard/index.vue
1. 在一些使用场景中，确认键点击动作是否自动隐藏键盘可隐藏包含着业务逻辑中，如#474
2. 键盘需添加自定义内容
3. 键盘的上边框，可能会导致误触点击 #477 
1. 增加属性isHideConfirm，用来控制确认键点击动作是否自动隐藏键盘
2. 增加slot，用来添加自定义内容
3. 阻止边框被点击 pointer-events none
无
> feat(number-keyboard): add prop isHideConfirm & slot

- components/codebox/index.vue
codebox的watch value的immediate拼写错误
修改正确的拼写
无
> fix(codebox): fix codebox with wrong watch options

- components/tab-picker/index.vue
1. 当`default-value`有初始值时，`tab-bar`默认选中的是第一项而非最后一项，体验不佳 #488 
2. 当更改了部分选项，但未保存直接点击取消后，`tab-bar`重新渲染有异常
1. 在`pans`的计算过程中，保证`currentTab`更新为最后一个`pan`的`name`
2. 将用于强制重新渲染的`tabsTmpKey`挂在`tabs`上，使得取消操作时的整个`tabs`可被重新渲染
无
> fix(tab-picker): some exceptions in tabs rendering

- components/toast/toast.vue
fix #485
toast在android4.4.4中，top、bottom位置不准确。经过测试发现是top、bottom会将md-popup-box加上absolute定位，但没有赋值默认的left值，出现兼容问题
给md-popup-box具体的定位
无
> fix(toast): fix toast in Android v4.4.4 wrong postion with top or bottom

- components/check/list.vue
fix #491
check-list、selector(多选模式使用check-list)点击icon时，没有反应。原因是check-list内置了md-check，点击icon时触发了md-check向inject中rootGroup的check方法，同时也触发了check-list的click回调再次调用rootGroup的toggle方法，导致重复调用出现bug
check-list中对md-check阻止默认行为
无
> fix(check-list): fix click md-icon without any action bug

- build/rollup/build-component.rollup.js
打包 `components` 组件的时候，这行代码不会被触发 `resultLog('success', 'Build **Components** Complete!')`，因为方法 `compileVueAndReplace` 没有 `resolve`。
无
无
> fix(build): resolved 'build components complete' log

- components/amount/index.vue
- components/amount/test/index.spec.js
背景描述
in transition mode, when the animation percent is 100%, the formateValue 's computed will lose precision
主要改动
when the animation percent is 100%, set the "formateValue"  as "toValue" and then return
需要注意
none
> fix(amount): fixed the loss of precision in animation mode

- components/input-item/index.vue
- components/input-item/test/index.spec.js
当使用虚拟键盘向InputItem输入字符时，maxlength无法限制字符长度。
ps: 初始化赋值已限制字符长度
在键盘输入事件时增加字符长度校验
无
> fix(input-item): limit the length of characters entered by the virtual keyboard

- components/_style/global.styl
ul, li, p 等格式化标签内部未去除默认样式，影响使用体验
global.styl增加部分reset样式
> fix: add global reset style

- components/swiper/index.vue
- components/swiper/test/index.spec.js
是否用户滚动页面行为的判断存在问题，无法区分touchmove轨迹“拐弯”的情况，会造成无法正常翻页#540
重写$_isScroll方法，根据滚动夹角判断是否用户滚动页面行为
是否阻塞正常滚动
> fix(swiper): refactor user scrolling judgment by touch angle

- components/action-bar/test/__snapshots__/demo.spec.js.snap
- components/activity-indicator/test/__snapshots__/demo.spec.js.snap
- components/button/index.vue
- components/button/test/__snapshots__/demo.spec.js.snap
- components/cashier/test/__snapshots__/demo.spec.js.snap
- components/dialog/test/__snapshots__/demo.spec.js.snap
- components/result-page/test/__snapshots__/demo.spec.js.snap
button 原有的 defaultSlot wrapper 是 p 标签, 存在样式没有重置的问题，且现在 slot 的内容多种多样，因此将 defaultSlot 的 wrapper 改为 div 标签
修改 button defaultSlot wrapper 标签 p -> div
是否影响原有样式
> fix(button): change default slot wrapper from p to div

- components/action-bar/README.en-US.md
- components/action-bar/README.md
- components/action-bar/demo/cases/demo3.vue
- components/action-bar/index.vue
- components/result-page/README.en-US.md
- components/result-page/README.md
- components/result-page/index.vue
ActionBar和ResultPage内部使用`Button`但可配置项过少，故补充一些配置属性 #544 
增加`type `, `plain`, `round`, `inactive`, `loading`, `icon`, `iconSvg`(根据设计规范，无`inline`和`size`)
出现在配置中的以上属性有**更高的优先级**，原来部分属性值作为默认值（如ActionBar默认最后一个按钮类型为`plain`为`false`，其他按钮为`true`）
> feat(action-bar & result-page): add props for buttons configration

- components/dialog/README.en-US.md
- components/dialog/README.md
- components/dialog/index.js
- components/dialog/test/index.spec.js
单例模式下配置中缺少`onShow, onHide`
增加show, hide事件监听，并调用相应的handler
为防止事件在绑定完成前触发，将`value`在组件构造时初始值改为`false`，当事件监听绑定完成后再赋值为`true`
https://github.com/didi/mand-mobile/pull/551/files#diff-a47b2bce0b46780cec0f267d1ecc87ccR62
> feat(dialog): add show/hide handler to instance dialog

- components/input-item/README.en-US.md
- components/input-item/README.md
- components/input-item/demo/cases/demo1.vue
- components/input-item/index.vue
- components/input-item/test/__snapshots__/demo.spec.js.snap
- components/input-item/test/index.spec.js
一、 缺少对特殊表单值（如带掩码的*身份证号，手机号*）的预览场景支持，此场景需衍生出一种特殊状态**预填展示时**，与**正常输入时**相比有以下几种特殊交互：
* 当用户做出编辑操作，如点击退格键及其他字符键点击时，先**清空预填值**
* 用于预填展示时和正常输入状态是表单类型可能不一致，当预填值被清空后需**将表单类型切换至输入状态的表单类型**
二、优化使用虚拟键盘的虚拟光标闪烁逻辑，**当表单处于编辑状态时不闪烁，停止编辑500ms后开始闪烁**
增加`preview-type`，用于设置表单**预填展示时**的类型
```html
<md-input-item
type="bankCard" 
preview-type="text" 
title="银行卡号"
value="6222 **** **** 1234"  
></md-input-item>
<md-input-item
type="bankCard"
:preview-type.sync="previewType" 
title="银行卡号"
value="6222 **** **** 1234"
></md-input-item>
```
`preivew-type`引入后，表单类型在不同状态切换时转换是否正常
> feat(input-item): add prop preview-type & optimize virtual cursor

- components/tab-bar/index.vue
fix #567
tab-bar的父级宽度使用vw + 百分比，会导致内部flex计算数值不准确，导致内部item宽度变化，最终触发死循环计算reflow
md-tab-bar-item添加flex: auto
无
> fix(tab-bar): fix tab-bar with reflow

- components/date-picker/README.en-US.md
- components/date-picker/README.md
- components/date-picker/demo/cases/demo2.vue
- components/date-picker/index.vue
- components/picker/README.en-US.md
- components/picker/README.md
- components/picker/index.vue
- components/picker/mixins/index.js
- components/picker/picker-column.vue
- components/picker/test/index.spec.js
Picker 和 DatePicker 列数据发生变化时，后面所有列默认回到顶部，某些场景体验不佳。通过增加`keep-index`，控制当前一列数据发生变化时，后面列保留上次一停留位置。
在列数据发生变化时
* 设置列数据时不再[默认回到顶部](https://github.com/didi/mand-mobile/blob/feat_picker_keep_index/components/picker/picker-column.vue#L486)
* 在列scoller重新初始化后，增加[resetScrollerPosition](https://github.com/didi/mand-mobile/blob/feat_picker_keep_index/components/picker/picker-column.vue#L230)
当列数据长度变更时，上一次停留位置超出可选范围的异常处理。如上一次选中3月31日，切换至2月
> feat(picker & date-picker): add prop keep-index

- components/_style/mixin/theme.components.styl
- components/textarea-item/README.en-US.md
- components/textarea-item/README.md
- components/textarea-item/demo/cases/demo0.vue
- components/textarea-item/index.vue
- components/textarea-item/test/__snapshots__/deme.spec.js.snap
- components/textarea-item/test/cases/demo0.vue
- components/textarea-item/test/index.spec.js
[issues 589](https://github.com/didi/mand-mobile/issues/589)
增加delete icon
关于这个图片是否需要上线居中, 现在暂时居上, 防止delete icon根据文字长度变化而变化, 固定在上面方便用户操作
> Feat textarea item delete icon

- components/textarea-item/index.vue
#589 这次在交互上改进下
小叉叉在失去焦点就消失, foucs的时候又重新显示焦点
> feat(textarea-item): hide delete icon when blur #589

- components/scroll-view/README.en-US.md
- components/scroll-view/README.md
- components/scroll-view/index.vue
- components/scroll-view/test/index.spec.js
1. 增加getOffsets，获取当前滚动位置
2. watch autoReflow，用于解决其动态设置问题。在某些场景如#595中，开启了autoReflow后会导致scrollview隐藏时，滚动位置被重置的问题，这种情况需要根据scrollview的展示状态动态设置autoReflow
> feat(scroll-view): add method getOffsets

- components/swiper/index.vue
- components/swiper/test/index.spec.js
1. 当窗口尺寸变更时，Swiper会被重新初始化导致index重置。在系统键盘弹起导致的窗口尺寸的场景下#596，重新初始化会降低使用体验。因此在窗口尺寸时需缓存当前index，保证Swiper停留在当前索引项目上。
2. 其他的代码优化
1. window resize的handler中缓存当前index，Swiper初始化以index为准来计算相关尺寸。
2. 原来代码中开始轮播有的调用`play`，有的调用`$_startPlay`，将其统一至调用`play`。
3. play的第一个参数可变更Swiper轮播停留时长，但直接修改prop中的`autoplay`，会有警告。增加私有变量`duration`取代`autoplay`。
2，3两点的变动，会给轮播停留时长造成一定影响，需认真review相关代码！！
> fix(swiper): keep index when window resizing & code optimizating

- components/swiper/index.vue
- components/tab-bar/index.vue
修复 #599 ，`resize`事件导致的若干问题
主要在 `swiper` 和`tabBar`两个组件中， 在`activated`、`deactivated`两个生命周期 进行 `resize` 事件的绑定与解绑
无
> fix(swiper,tab-bar): fix resize behavior

- components/tab-bar/index.vue
TabBar在计算是否可滚动时的contentWidth是所有item宽度之和，但是当item宽度存在小数点时，使用offsetWidth无法取到精确值而造成1px左右误差，使得contentWidth大于wrapperWidth而出现滚动。如iphone6 safari
item宽度获取由offsetWidth，改为getBoundingClientRect
> fix(tab-bar): error in calculating the width of tab items

- components/skeleton/index.vue
没有对 props title 进行判断，导致 title 一直显示
对 title 进行判断
无
> fix(skeleton): fix title always displayed

- components/tab-bar/index.vue
修复 keep-alive 模式下 tab-bar 的 resize 行为
tab-bar 在 keep-alive 下 两个生命周期，绑定和解绑 resize 事件
无
> fix(tab-bar): fix resize behavior in keep-alive mode

- components/stepper/index.vue
- components/stepper/test/index.spec.js
#614 
1. 当存在数据双向绑定时，input修改可能会立即触发数据自动修正，导致无法正常输入
2. 对于边界值的限制过于严格，即对于当前值在限制区间内，但加减step之后会在限制区间外的情况，不做限制，加减后靠自动修正回到限制区间内
1. 增加编辑中的状态，当input修改中不触发数据自动修正
2. 使用当前值而不是加减step后的值 判断是否在限制区间内逻辑
是否引入其他边界情况
> fix(stepper): data binding trigger unnecessary checks & maximum and minimum check release boundary value

- components/action-bar/index.vue
- components/drop-menu/index.vue
- components/number-keyboard/index.vue
- components/picker/picker-column.vue
ActionBar, NumberKeyboard 补充底部安全区留白兼容写法，Picker，Selector，DropMenu底部安全区不留白
> fix: supplement safe-area padding and remove unused

- components/landscape/README.en-US.md
- components/landscape/README.md
- components/landscape/demo/cases/demo0.vue
- components/landscape/index.vue
- components/popup/README.md
- components/radio/README.en-US.md
- components/radio/README.md
为 `landscape` 添加 `transition` 属性，使用户能自选动画 
1. 为 `landscape` 添加 `transition` 属性
2. 修改了文档的一些错别字
无
> feat(landscape): add props transition for landscape & correct some typos

- components/textarea-item/index.vue
- components/textarea-item/test/index.spec.js
在popup组件里使用textarea-item, 高度始终是0
textarea-item组件,在初始化的时候,如果组件这个没有显示出来(比如display:none), 这个时候计算的scrollHeight是0, 然后display:block的时候并没有重新计算scrollHeight, 这个时候组件的高度任然是0
> fix(textarea-item): avoid height calculations

- components/swiper/index.vue
如果是userScrolling(用户只是想上下滑动屏幕,不是左右滑动滑块), autoplay意外被中断
复现: https://didi.github.io/mand-mobile/examples/#/swiper 第一个swiper, 鼠标按住想上滑一下, 松手, 即可复现
滑动结束, 恢复自动播放
> fix(swiper): autoplay fails  when userScrolling

- components/scroll-view/index.vue
- components/selector/test/__snapshots__/demo.spec.js.snap
- components/tab-bar/test/__snapshots__/demo.spec.js.snap
- components/tab-picker/test/__snapshots__/demo.spec.js.snap
- components/tabs/test/__snapshots__/demo.spec.js.snap
- components/tip/index.js
- components/tip/test/index.spec.js
- components/tip/test/tip-wrapper.vue
当Tip在ScrollView中使用时，因为Scrollview内部是模拟滚动，所以tip展示时因为无法准确选中滚动容器而导致位置计算错误。
Scrollview中通过`scroll-wrapper`属性标记出滚动容器，tip内部判断滚动容器的条件增加是否具有该标记。
PS: 该标记属性也可用于用户自定义布局中通过`translate`实现的模拟滚动场景
> fix(tip): mark scrolling wrapper in ScrollView

- components/captcha/README.en-US.md
- components/captcha/README.md
- components/captcha/index.vue
- components/captcha/test/index.spec.js
验证码第一次展示时，默认自动触发了`send`事件，无法控制此时机
增加属性`auto-send`，当其为`false`时，验证码第一次展示不自动触发`send`事件，需用户点击`发送`按钮后触发
> feat(captcha): add prop auto-send for trigger send event automatically

- components/scroll-view/index.vue
fix #642 
scroll-view使用scroll-view-refresh组件，下拉刷新，手势滑动到最底部并没有触发refreshActive事件，而是在向上滑动时才会触发
修改refreshActive事件触发位置
无
> fix(scroll-view): fix scroll-view-refresh wrong emit refreshActive

- components/tabs/demo/cases/demo0.vue
官方文档demo实例代码错误
旧
```css
.content
padding 12px 0     <----------
font-size 28px
background #FFF
padding 20px
line-height 1.5
box-sizing border-box
```
新
```css
.content
margin 12px 0     <----------
font-size 28px
background #FFF
padding 20px
line-height 1.5
box-sizing border-box
```
无
> doc(tabs): fix double padding

- components/check/README.en-US.md
- components/check/README.md
- components/check/box.vue
- components/check/demo/cases/demo4.vue
- components/check/group.vue
- components/check/index.vue
- components/check/test/index.spec.js
CheckGroup增加全选/全不选和反选功能 #648 
CheckGroup增加接口方法toggleAll
```js
toggleAll(true) // 全选
toggleAll(false) // 全不选
toggleAll() // 反选
```
禁用的选项，需保持初始化时的状态，调用toggleAll后不会改变
> feat(check-group): add method for full selection and reverse selection

- components/textarea-item/demo/cases/demo0.vue
- components/textarea-item/index.vue
- components/textarea-item/test/index.spec.js
异步数据导致textarea没有撑开
watch value的时候, 在nextTick里执行高度计算
> fix(textarea-item): aync data causes highly computational bugs

- components/image-reader/image-processor.js
避免jpgencoder库被重复加载（如微前端模式下）
侦测并复用全局对象
无
> fix(image-reader): avoid importing jpegencoder repeatedly

- components/button/index.vue
fix #663
链接按钮文字显示不正确
修正链接按钮行高
无
> fix(button): correct link button line-height 

- components/tab-bar/index.vue
跟之前的PR #601 同样的问题，上次只是修复了tab item，tab wrapper的尺寸也同样的问题
wrapper宽度获取由offsetWidth，改为getBoundingClientRect
> fix(tab-bar): error in calculating the width of tab wrapper

- components/amount/demo/cases/demo3.vue
- components/amount/number-capital.js
修复中文货币单位不正确的问题
由 `元角分毫厘` 修正为 `元角分厘毫`
无
> fix(amount): 修复中文货币单位不正确的问题

- components/number-keyboard/key.vue
在部分浏览中，touchstart preventDefault无效，导致touchstart和click会重复触发，从而导致点击动作被重复处理
对同时绑定了touchstart和click两种事件进行拦截处理，当toustart被优先触发后，避免click事件再次被响应
> fix(number-keyboard): avoid repeated triggering of click and touchstart

- components/popup/README.en-US.md
- components/popup/README.md
如果使用 `jsx/tsx` 语法，直接使用 `only-close` 属性会受到影响不被 `jsx/tsx` 识别，在 [babel-plugin-transform-vue-jsx](https://github.com/vuejs/babel-plugin-transform-vue-jsx#difference-from-react-jsx) 库提供了 **propsOnXXX** 开头的属性即可被 `jsx/tsx` 识别。
新增 `only-close` 中英文备注
无
> doc(popup): use propsOnlyClose in jsx or tsx

- components/tip/index.js
- components/tip/test/tip-wrapper.vue
tip 组件子组件是没有属性的原生标签的时候会报错
```
<md-tip content="不错哟" placement="top" ref="tip">
<span>点击我</span>
</md-tip>
```
在 `render` 方法里，对 `firstNode.data` 做了一次初始化
```
firstNode.data = firstNode.data || {}
```
修改了测试用例 `tip-wrapper.vue`
使用了没有属性的原生组件做子元素
> fix(tip): Tip components subcomponents are native tags with no properties that will report an error

- .github/workflows/preview.yml
Reverts didi/mand-mobile#718
`pull_request_target` 配合 `refs/pull/${{ github.event.pull_request.number }}/merge` 有安全隐患，先回滚到 `pull_request`。
https://github.com/afc163/surge-preview/pull/100
> Revert "chore: update preview.yml"

- components/image-reader/image-processor.js
有些浏览器已经做了自动修复图片角度的功能，此时无需再代码修正图片，否则图片再次旋转不符合预期
当浏览器不自动修复图片角度问题时，再用代码修复图片角度。（检测浏览器是否已做修正，在我们线上线上项目运行小半年了，没有问题，此次有兄弟项目组发现该组件拍照有问题，故提出此pr）
主要判断了浏览器是否有自动修复的功能，有的话，则不再修正，否则走原来的修正逻辑
可以chrome浏览器试试，此浏览器已做图片修正
> fix image orientation

- components/input-item/cursor.js
格式化的表单，当光标位于中间时，插入字符光标会先回到字符串最后，再回到正确位置 #749 
减少设置光标的异步动作延迟时间
兼容问题，部分安卓设备可能会光标设置无效
> fix(input-item): shorten interval to set cursor position asynchronously

- components/ruler/index.vue
初始化时，基于scope的设置存在不可滚动区域时，需修正内部scroller位置（此时ruler初始化未完成），但因为滚动回调内只处理初始化完成后的滚动，所以此修正操作就跳过了，导致ruler位置异常。#748
scroller的渲染回调用处理未完成时的动作
> fix(ruler): fixed scrolling position when ruler is not initialized

- site/docs/design/vision/font.en-US.md
- site/docs/design/vision/font.md
- site/docs/design/vision/icon.en-US.md
- site/docs/design/vision/icon.md
- site/docs/design/vision/layer.en-US.md
- site/docs/design/vision/layer.md
官网设计模块，字体图标层级页面示例图片在移动端变形
使用媒体查询适配字体图标层级页面示例图片在移动端的显示
字体页面表格图片由table标签替换
无
> fix(site): 适配移动端图片压缩问题

- site/docs/design/preface/introduce.en-US.md
- site/docs/design/preface/viewpoint.en-US.md
- site/docs/design/preface/viewpoint.md
- site/docs/design/principle/attitude.en-US.md
- site/docs/design/principle/attitude.md
- site/docs/design/principle/clear-controllable.en-US.md
- site/docs/design/principle/clear-controllable.md
- site/docs/design/principle/intuition.en-US.md
- site/docs/design/principle/intuition.md
首页设计模块，Fd+介绍、设计价值观、直观简单、清晰可控、安全感知、态度专业页面在部分浏览器和移动端图片放缩
使用媒体查询将Fd+介绍、设计价值观、直观简单、清晰可控、安全感知、态度专业页面图片能在浏览器和移动端适配
无
> fix(site): 修改首页设计模块兼容性问题

- components/agree/index.vue
组件内为icon的宽高设置了auto属性。导致svg图标会被渲染成默认尺寸（250px x 150px）
删除 width:auto 、height:auto、line-height:1
> fix: 删除agree组件中icon的默认宽高样式

- components/popup/title-bar.vue
vue与vue-template-compiler@2.6.14以上版本报错
修改components/popup/title-bar.vue根节点class
> fix(popup-title-bar): vue与vue-template-compiler@2.6.14以上版本报错
