didi/mand-mobile

- examples/main.indemand.js
> Revert "fix: fix fastclick export error[#1]"

- build/rollup/rollup-plugin-config.js
- build/rollup/rollup-plugin-example-config.js
when user run `npm run dev`, it may occur error for those who install dependence with `cnpm`, this pr would fix it .
> Fix issue #1

- .babelrc
- build/webpack/webpack.dev.conf.js
- examples/single-component-app.vue
- package.json
build: now you can develop single component by "npm run dev -- --component=xxx"
> build: optimize dev script

- components/swiper/index.vue
feat(swiper): enable drag to switch page in 'fade' mode
> feat(swiper): enable drag to switch page in 'fade' mode

- components/image-viewer/README.md
- components/image-viewer/demo/cases/demo0.vue
- components/image-viewer/index.vue
- components/image-viewer/test/index.spec.js
Add `v-model` support for **image viewer**
> feat(image-viewer): Add v-model support[#42]

- components/picker/index.vue
- components/picker/picker-column.vue
column shouldn't be refreshed at data initializaion #50 & data immutable
> fix(picker):column shouldn't be refreshed at data initializaion #50

- .gitignore
- build/rollup/build-vw-responsive.js
- package.json
> Feature vw support

- components/agree/demo/cases/demo0.vue
- components/agree/index.vue
修复在嵌套HTML标签内容时，会有flexbox显示挤压的问题。
> fix(agree): flexbox display bug

- components/tab-bar/demo/cases/demo10.vue
- components/tab-bar/demo/index.vue
- components/tab-bar/index.vue
> feat(tab-bar): add scrollable support #144

- components/input-item/index.vue
> fix(input-item): remove setting cursor for native type

- components/tab-picker/demo/data.json
- components/tab-picker/index.vue
- components/tabs/index.vue
- components/tabs/tab-pane.vue
When manipulate with TabPicker option list, it will trigger body scroll as well. This PR is try to fix this problem.
> Fix TabPicker scroll problem

- components/input-item/index.vue
> fix(input-item): fix input-item with virtualKeyboard in vue@2.6 bug

- build/rollup/rollup-plugin-config.js
> build: fix css assets not transform bug

- components/_util/render.js
- components/_util/scroller.js
> fix(utils): fix scroller zooming

- components/popup/index.vue
support for toast show and hide synchronous calls
#341 
Mark: 
* 需验证去掉popup box 异步展示的逻辑后，对popup box动画的影响（老版本vue中动画无效）
* 需cherry-pick至1.x分支
> fix(popup): display popup box synchronously

- components/swiper/index.vue
> fix(swiper): remove all listeners after destroyed

- components/input-item/demo/cases/demo5.vue
- components/input-item/index.vue
- components/input-item/test/index.spec.js
修复input-item在插槽发生变化的时候无法正常渲染的问题
>  fix: input-item slot render error

- build/rollup/rollup-plugin-stylus-compiler.js
> build(rollup): fix typo

- components/activity-indicator/roller.vue
> fix(progress): hide inner circle when value is 0

- components/stepper/README.en-US.md
- components/stepper/README.md
- components/stepper/index.vue
- components/stepper/test/index.spec.js
> feat(stepper): add events(add & reduce)

- components/water-mark/index.vue
- components/water-mark/test/__snapshots__/demo.spec.js.snap
1. water-mark use canvas to render content
2.update water-mark snapshot
> feat(water-mark):optimize with canvas

- components/ruler/demo/cases/demo0.vue
- components/ruler/demo/cases/demo1.vue
- components/ruler/demo/cases/demo2.vue
- components/ruler/index.vue
- components/water-mark/index.vue
> fix(ruler,water-mark): change canvas font family

- components/swiper/index.vue
修复swiper在设置isLoop为true时，autoplay失效bug
> fix(swiper): fix swiper bug with isLoop & autoplay

- components/selector/README.en-US.md
- components/selector/README.md
- components/selector/demo/cases/demo4.vue
- components/selector/demo/index.vue
- components/selector/index.vue
- components/selector/test/__snapshots__/demo.spec.js.snap
- components/selector/test/cases/demo4.vue
- components/selector/test/demo.spec.js
- components/selector/test/index.spec.js
feat #296
Selector需要支持多选
Selector增加multi属性为true时可以多选
multi为true时，okText属性不能为空
> feat(selector): support multi select

- components/captcha/test/__snapshots__/demo.spec.js.snap
- components/cashier/test/__snapshots__/demo.spec.js.snap
- components/codebox/test/__snapshots__/demo.spec.js.snap
- components/input-item/test/__snapshots__/demo.spec.js.snap
- components/number-keyboard/board.vue
- components/number-keyboard/key.vue
- components/number-keyboard/test/__snapshots__/demo.spec.js.snap
> fix(number-keyboard): numberkeyboard action

- components/button/README.en-US.md
- components/button/README.md
- components/button/demo/cases/demo0.vue
- components/button/demo/cases/demo1.vue
- components/button/index.vue
- components/button/test/__snapshots__/demo.spec.js.snap
- components/button/test/cases/demo0.vue
- components/button/test/cases/demo1.vue
增加按钮loading状态
增加新属性 loading
不同类型按钮下loading状态展示是否正常
> feat(button): add props loading

- components/amount/number-capital.js
> fix(amount): conversion of negative numbers to capitals

- components/_style/mixin/theme.components.styl
- components/dialog/README.en-US.md
- components/dialog/README.md
- components/dialog/demo/cases/demo0.vue
- components/dialog/dialog.vue
- components/dialog/test/__snapshots__/demo.spec.js.snap
- components/dialog/test/cases/demo0.vue
1. 对话框操作按钮属性增加禁用态，加载中，图标
2. 更改radius大小
3. 增加header插槽
> feat(dialog): add prop disabled to btns & add slot header & update style

- site/mfe.blog.config.js
- site/theme/default/App.vue
- site/theme/default/Home.vue
- site/theme/default/assets/js/home.config.js
- site/theme/default/components/Footer.vue
* 请认真阅读[开发指南](https://didi.github.io/mand-mobile/#/zh-CN/docs/development)
* fork **dev分支**
* 按照规范命名分支
* 需通过测试
* 提交PR至**dev分支**
* 标题规则：type(scope):description，参考[规范](https://didi.github.io/mand-mobile/#/zh-CN/docs/development?anchor=Commit%E8%A7%84%E8%8C%83)
* 内容描述，参考"PR 内容区"
> site: update configration & update style

- .travis.yml
open travis on the dev branch
add dev to `.travis.yml`
> chore(travis): add dev branch

- components/picker/README.en-US.md
- components/picker/README.md
picker文档描述错误
修改picker的readme
无
> doc(picker): fix picker wrong doc word

- components/check-base/box.vue
- components/check/box.vue
- components/check/test/__snapshots__/demo.spec.js.snap
- components/index.js
- components/radio-box/index.vue
- components/radio-group/index.vue
- components/radio/README.en-US.md
- components/radio/README.md
- components/radio/box.vue
- components/radio/demo/cases/demo0.vue
- components/radio/demo/cases/demo1.vue
- components/radio/demo/cases/demo2.vue
- components/radio/demo/cases/demo3.vue
- components/radio/demo/cases/demo4.vue
- components/radio/demo/cases/demo5.vue
- components/radio/demo/index.vue
- components/radio/group.vue
- components/radio/index.vue
- components/radio/test/__snapshots__/demo.spec.js.snap
- components/radio/test/cases/demo3.vue
- components/radio/test/cases/demo4.vue
- components/radio/test/cases/demo5.vue
- components/radio/test/demo.spec.js
- components/radio/test/index.spec.js
新增radiio-box和radio-group，与check系列组件配套 #543
> feat(radio): add radio-group & radio-box

- components/_style/mixin/theme.components.styl
- components/textarea-item/demo/cases/demo0.vue
- components/textarea-item/demo/cases/demo2.vue
- components/textarea-item/index.vue
- textarea-item 组件的部分全局样式没有用上, 这次加上
- texarea-item demo的样式调整
> Fix textarea style

- components/tip/README.en-US.md
> doc(tip): update readme

- components/_style/mixin/theme.components.styl
互换zindex， toast zindex 1700，landscape zindex 1600，解决toast被遮挡
> fix(toast & landscape): swap zindex

- components/_style/global.styl
移除全局样式reset中的非必须样式，仅保留margin和padding
> style: remove some non-essential styles

- components/textarea-item/index.vue
解决bug: 输入文字 => 点击图标删除 => 重新输入 => bug:删除按钮没有出现
> fix(textarea-item): delete icon did not appear normally

- components/notice-bar/demo/cases/demo8.vue
- components/notice-bar/demo/index.vue
- components/notice-bar/index.vue
- components/tabs/tab-pane.vue
1. 修复`tabs`在滚动时，可能带来的重绘问题
2. 修复`notice-bar`动态变化内容下，滚动不正确的问题
`tabs`和`notice-bar`组件
无
> fix(tabs,notice-bar): improve transition performance & improve notice-bar's performance with dynamic slot content

- components/amount/demo/cases/demo1.vue
- components/amount/index.vue
- components/amount/test/__snapshots__/demo.spec.js.snap
- components/amount/test/cases/demo1.vue
fix #644
amount组件使用千分符展示负数错误
修复展示问题；更新测试快照；添加demo
无
> fix(amount): fix amount display negative number

- components/result-page/index.vue
- components/result-page/test/index.spec.js
因为data初始化时有数据格式化，props不支持动态变更。#638
监听props变化，重新格式化数据，然后更新data
> feat(result-page): reactive props

- components/landscape/README.md
> doc(landscape): update readme

- components/textarea-item/README.en-US.md
- components/textarea-item/README.md
- components/textarea-item/demo/cases/demo0.vue
- components/textarea-item/index.vue
- components/textarea-item/test/index.spec.js
https://github.com/didi/mand-mobile/issues/699
给textarea-item增加formation api的支持
> feat(textarea-item): support formation (#699)

- components/date-picker/README.en-US.md
- components/date-picker/test/index.spec.js
- components/picker/README.md
- components/radio/group.vue
修复一些已知的问题
- 修复文档单词拼写错误 #690 
- 移除 `radio-group` 对 `value` 的类型约束 #693
> fix docs words & remove radio-group value type checking

- components/popup/index.vue
- components/swiper/index.vue
- components/water-mark/index.vue
- config/dev.env.js
- config/prod.env.js
- config/test.env.js
- package.json
> fix(build): replace NODE_ENV with MAND_ENV in some components

- components/image-reader/image-processor.js
- components/stepper/index.vue
- fix stepper bug #731 
- fix image-reader bug #734
> Fix stepper

- site/docs/design/vision/font.en-US.md
- site/docs/design/vision/font.md
- site/docs/design/vision/icon.en-US.md
- site/docs/design/vision/icon.md
- site/docs/design/vision/layer.en-US.md
- site/docs/design/vision/layer.md
- site/mfe.blog.config.js
* 请认真阅读[开发指南](https://didi.github.io/mand-mobile/#/zh-CN/docs/development)
* fork **dev分支**
* 按照规范命名分支
* 需通过测试
* 提交PR至**dev分支**
* 标题规则：type(scope):description，参考[规范](https://didi.github.io/mand-mobile/#/zh-CN/docs/development?anchor=Commit%E8%A7%84%E8%8C%83)
* 内容描述，参考"PR 内容区"
> feat:修改官网ui

- package-lock.json
- site/docs/design/principle/attitude.en-US.md
- site/docs/design/principle/attitude.md
- site/docs/design/vision/color.en-US.md
- site/docs/design/vision/color.md
- site/docs/design/vision/layout.en-US.md
- site/docs/design/vision/layout.md
- site/mfe.blog.config.js
设计模块UI改版
1、态度专业模块
2、颜色模块
3、布局模块
三块的文档
设计模块的界面样式
> doc: 增加 态度专业、颜色和布局模块的文档

- site/docs/design/principle/attitude.en-US.md
- site/docs/design/principle/attitude.md
- site/docs/design/vision/layout.en-US.md
- site/docs/design/vision/layout.md
设计模块ui界面修改
态度专业页面 && 布局页面移动端适配
界面
> docs: 态度专业页面 && 布局页面移动端适配

- components/_locale/lang/zh-CN.js
- components/captcha/demo/cases/demo2.vue
- components/captcha/demo/index.vue
- components/captcha/index.vue
- components/captcha/test/cases/demo2.vue
- components/captcha/test/demo.spec.js
- components/codebox/index.vue
添加验证码组件半屏模式
captcha 组件修改如下
增加半屏样式
增加属性
type:  String // 验证码组件模式类型
disableSend:  Boolean // 发送验证码按钮是否禁用
subtitle: String // 副标题
codebox 组件增加属性如下
增加属性
isErrorStyle:  Boolean // 是否展示错误样式
对安卓手机，系统键盘弹出时，页面上下大幅度跳动做了特殊处理
已测试大部分机型兼容
> feat: 验证码组件增加半屏模式

- components/captcha/README.en-US.md
- components/captcha/README.md
- components/codebox/README.en-US.md
- components/codebox/README.md
> Feature add captcha format

- components/license-plate/index.vue
> feat: 修缮es6语法格式

- types/mand-mobile.d.ts
* 请认真阅读[开发指南](https://didi.github.io/mand-mobile/#/zh-CN/docs/development)
* fork **dev分支**
* 按照规范命名分支
* 需通过测试
* 提交PR至**dev分支**
* 标题规则：type(scope):description，参考[规范](https://didi.github.io/mand-mobile/#/zh-CN/docs/development?anchor=Commit%E8%A7%84%E8%8C%83)
* 内容描述，参考"PR 内容区"
> feat: 增加车牌组件ts校验文件

- components/dialog/index.js
> feat: 弹窗icon优化

- components/dialog/index.js
- components/icon/index.vue
- components/license-plate/index.vue
* 请认真阅读[开发指南](https://didi.github.io/mand-mobile/#/zh-CN/docs/development)
* fork **dev分支**
* 按照规范命名分支
* 需通过测试
* 提交PR至**dev分支**
* 标题规则：type(scope):description，参考[规范](https://didi.github.io/mand-mobile/#/zh-CN/docs/development?anchor=Commit%E8%A7%84%E8%8C%83)
* 内容描述，参考"PR 内容区"
> feat:车牌组件弹窗样式优化
